# Generated by Django 4.2 on 2024-07-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.SmallIntegerField(choices=[(0, 'EMPLOYEE USER'), (1, 'RESTAURANT USER')], default=1),
            preserve_default=False,
        ),
    ]
